
#*************** particle filter parameters ************************

#number of particles per target
num_particles: 300

#when a new filter/target is launched, XY space is sampled along init_delta_xy from the first detection point 
init_delta_xy: 0.3

#when a new filter/target is launched, VxVy space is sampled along init_delta_vxy from 0
init_delta_vxy: 0.5

#resampling standard deviation applied at the end of each filter iteration along XY dimensions
sigma_resampling_xy: 0.01

#resampling standard deviation applied at the end of each filter iteration along VxVy dimensions
sigma_resampling_vxy: 0.1

#person radius used in LEG and BODY matching functions. Smaller the radius, more precise should be detections
person_radius: 0.35

#LEG and BODy cost function parameters. 
matching_legs_alpha: 0.1
matching_legs_beta: 10
matching_bearing_alpha: 0.1
matching_bearing_beta: 10


#****************** tracker parameters *********************************

#If targets closer than this distance, merging function is called
minimum_distance_between_people: 0.25

#Lower probabilities are treated as ZERO
minimum_association_prob: 0.000001

#detections farther than this distance are ignored [m]
max_detection_distance_accepted: 5

#detections closer than this distance are ignored [m]
min_detection_distance_accepted: 0.1

#leg detections with azimut gerater than this are ignored [deg]
max_detection_azimut_accepted: 60

#If a target, not in occlusion, remains max_consecutive_uncorrected_iterations without having associated any detection, the target is deleted
max_consecutive_uncorrected_iterations: 8

# a CANDIDATE target requires minimum_iterations_to_be_target to be considered as a LEGGED target
minimum_iterations_to_be_target: 10

# a LEGGED target requires minimum_iterations_to_be_visually_confirmed iterations with FACE or BODY detections associated, to be considered as VISUALLY_CONFIRMED
minimum_iterations_to_be_visually_confirmed: 5

# a VISUALLY_CONFIRMED target requires minimum_iterations_to_be_friend more iterations with FACE or BODY detections associated, to be considered as a FRIEND
minimum_iterations_to_be_friend: 5

#DEPRECATED! minimum number of pixels for appearance model 
minimum_appearance_region_size: 100


#****************** ROS node options *************************************

#verbose mode. 0->Off, 1->On
verbose_mode: 0

#send visualization markers corresponding to body detections , 0->Off, 1->On
view_body_detections: 1

# ratio of particles which are sent as visualization markers
ratio_particles_displayed: 0.1
